title: AQUARELA Status
buildFuture: true
defaultContentLanguage: pt
languageCode: en
baseURL: https://status.aquarela.app
params:
  disableDarkMode: true
  shortDateFormat: 15:04 — Jan 2
  down: "#e60000"
  systems:
    - name: AQUARELA Cloud Server [Powered by Cloudez]
      category: North America
    - name: AQUARELA Baremetal SERVER
      category: Latin America
    - category: lala
      name: AQUARELA Main Services
    - name: AQUARELA Main Repository
      category: lala
    - name: AQUARELA Backup Repository [DEPRECATED\
      category: lala
  dateFormat: January 2, 2006 at 3:04 PM
  brand: "#0a0c0f"
  headerTextColor: white
  logo: https://ik.imagekit.io/aquarela/aquarela-logo-mobile_1L3DYGIs6K.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Latin America
      closed: false
      description: ""
    - name: North America
      closed: false
      description: ""
    - untitled: true
      name: lala
      description: ""
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
